### ISSUE TITLE
Code scanning support for other programming languages

### ISSUE THREAD

**Issue by ghost** [NickLiffen/ghas-enablement#3]
Please extend the support for projects running with Python, Java  etc..

**Comment by NickLiffen** [comment]
Thanks @nawinto99 for your issue 💯 What do you mean extend support for projects running with Python, Java?

Do you mean provide a sample file for Python, Java, etc? Right now there is only a sample file for JavaScript, would you like one for other languages?

Just to clarify :)

**Comment by nawinto99** [comment]
Exactly @NickLiffen

- What if a project having multiple programming languages? ?
- Is there a way to automatically detect languages and replace the language matrix rather than hardcoding it?

```
matrix:
        language: [ 'javascript' ]
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
```
