### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by emilva** [NickLiffen/ghas-enablement#34]
Hi @NickLiffen 👋 

Some feature requests to help us onboard on a per-team basis:

1. In step one: make it possible to gather repos by team rather than language (https://docs.github.com/en/rest/reference/teams#list-team-repositories)
2. Set the branch name in `codeql-analysis.yml` based on the repo's default branch name

**Comment by NickLiffen** [comment]
Thanks for the feedback @emilva 👍 I will try and get these features addressed as soon as I can 👍

**Comment by emilva** [comment]
Great stuff @NickLiffen!

**Comment by agonzalez-plume** [comment]
For the default branch name, all you need to do is change the branches in the codeql-analysis.yml to say:

branches: [ $default-branch ]

When you check that file in, Github will change it to the default branch automatically

So do:

```
name: "CodeQL"

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
```
