### ISSUE TITLE
Unable to apply CodeQL to any branch that is not the default branch

### ISSUE THREAD

**Issue by benhorgen** [NickLiffen/ghas-enablement#89]
When using the script, I wasn't able to apply the CodeQL setting to branches that are not the `default` branch for their repo.

For example, if I specify `develop` in the .yaml file it will be applied to repos with a default branch of `develop` **but will also apply the CodeQL setting to the default branch of the other repos listed in the `repos.json` file**. 

In addition, it will not apply to the `develop` branch of that repo if the default branch is not `develop`.

Sample from codeql-analysis-javascript.yaml file:

```
on:
  push:
    branches: [develop]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [develop]
  schedule:
    - cron: "34 14 * * 0"
```

With the config above in my `codeql-analysis-javascript.yaml` and with two repos listed in the `repos.json` file the result is:  Both repos will get CodeQL enabled. But only against their default branches, regardless of the default branch name.
